name: deploy to environment

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ACCOUNT_ID: 721520867440

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install infrastructure
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: infrastructure

      - name: Install web
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: web

      - name: Build infrastructure and web
        run: |
          cd infrastructure
          yarn build
          yarn build:frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume:
            arn:aws:iam::${{ env.ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: Dynamically Set environment variables (dev, stage, prod)
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ ! -z "${{ github.event.ref }}" ]; then
            if [ "${{ github.event.ref }}" == "refs/heads/main" ]; then
              echo "NODE_ENV=dev" >> $GITHUB_ENV
              echo "DOTENV_CONFIG_PATH=./.env.dev" >> $GITHUB_ENV
            elif [ "${{ startsWith(github.event.ref, 'refs/tags/') }}" == "true" ]; then
              echo "NODE_ENV=stage" >> $GITHUB_ENV
              echo "DOTENV_CONFIG_PATH=./.env.stage" >> $GITHUB_ENV
            elif [ "${{ startsWith(github.event.ref, 'refs/tags/prod-') }}" == "true" ]; then
              echo "NODE_ENV=prod" >> $GITHUB_ENV
              echo "DOTENV_CONFIG_PATH=./.env.prod" >> $GITHUB_ENV
            fi
          fi

      - name: cdk synth
        run: |
          cd infrastructure && CDK_DEFAULT_ACCOUNT=${{ env.ACCOUNT_ID }} CDK_DEFAULT_REGION=${{ env.AWS_REGION }} NODE_ENV=${{ env.NODE_ENV }} DOTENV_CONFIG_PATH=${{ env.DOTENV_CONFIG_PATH }} npx cdk synth

      - name: deploy to ${{ env.NODE_ENV }}
        # configuring creds is not needed after using an IAM role provided through an OIDC Provider
        run: |
          cd infrastructure && NODE_ENV=${{ env.NODE_ENV }} DOTENV_CONFIG_PATH=${{ env.DOTENV_CONFIG_PATH }} npx cdk deploy --require-approval never

      - name: Cypress e2e tests for backend api 🧪
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          # record: true
          # group: e2e-tests
          # tag: branch-backend
          working-directory: infrastructure
        env:
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress e2e tests for front end 🧪
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          install: false
          # record: true
          # group: e2e-tests
          # tag: branch-front-end
          working-directory: web
        env:
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
